"""Rename assignment column

Revision ID: 69859f4d0367
Revises: 5647b51fe7cb
Create Date: 2020-08-13 16:01:19.216002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69859f4d0367'
down_revision = '5647b51fe7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('driver_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('assignment', 'drivers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('drivers', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('assignment', 'driver_names')
    # ### end Alembic commands ###
