version: 1
formatters:
  simple:
    format: '%(asctime)s [%(name)s] {%(pathname)s:%(lineno)d} [%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: output/avicena.log
    maxBytes: 1024000
    backupCount: 3
root:
  level: DEBUG
  handlers: [console, file]
