database:
  enabled: False
  url: postgres://rides:password@localhost:5432/rides_test
geocoder_key: 78bdef6c2b254abaa78c55640925d3db
trips_parser: LogistiCare
optimizer: GeneralOptimizer
seed: 10
merge_address_table_path: input/merge_address.csv
revenue_table_path: input/updated_rev_table.csv
driver_table_path: input/in_drivers.csv
output_directory: output/