database:
  url: postgres://localhost:5432/rides
  username: rides
  password: password
geocoder:
  vendor: OpenCage
  key: 1234
client_parser: LogistiCare
trips_file: trips.pdf
optimizer: GeneralOptimzer